user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

stream {
    upstream backend_receiver_health {
        server dnsmin_receiver:8000 fail_timeout=10 max_fails=10;
    }

    upstream backend_receiver_tcp {
        server dnsmin_receiver:5353 fail_timeout=10 max_fails=10;
    }

    upstream backend_receiver_udp {
        server dnsmin_receiver:5354 fail_timeout=10 max_fails=10;
    }

    server {
        listen 8080;
        proxy_pass backend_receiver_health;
    }

    server {
        listen 5353;
        proxy_pass backend_receiver_tcp;
    }

    server {
        listen 5354 udp;
        proxy_pass backend_receiver_udp;
        #proxy_responses 1;
    }
}